version: '3.9'

services:
  nginx:
    build:
      context: nginx
#    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - app

  app:
    build:
      context: shiny
#    container_name: shiny_app
    expose:
      - "3838"